### ISSUE TITLE
Empty Client Hints headers lead to incorrect detection

### ISSUE THREAD

**Issue by leonidboykov** [51Degrees/data-issues#7]
Sometimes we receive empty client hints:

``` yaml
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Mobile/15E148 Safari/604.1
Sec-CH-UA-Full-Version: ""
Sec-CH-UA-Mobile: ?0
Sec-CH-UA-Model: ""
Sec-CH-UA-Platform: ""
Sec-CH-UA-Platform-Version: ""
```

These client hints break the device detection and provide incorrect results. You may check it with [user-agent-tester](https://51degrees.com/developers/user-agent-tester) — the iPhone is marked as a _Desktop, Emulator_.

But if I remove all empty client hints

``` yaml
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Mobile/15E148 Safari/604.1
Sec-CH-UA-Mobile: ?0
```

the detection is way more accurate.

Can you confirm that this is a bug? Perhaps, this behavior may be fixed on the 51Degrees side.

**Comment by Tracy51D** [comment]
Hi @leonidboykov - This isn’t considered a bug. Client Hints are expected to be higher value/better information than the User-Agent so whenever we have the headers we evaluate those first.

The ‘Sec-CH-UA-Mobile: ?0’ mobile header indicates the device is a desktop in desktop mode. The pseudo header we construct combines the mobile and model headers so in this case we see ""?0.

Our suggestion would be for you to implement a check on your end where you choose not to include empty headers.

**Comment by leonidboykov** [comment]
@Tracy51D do you mean, these are expected results?

### With empty Client Hints

``` yaml
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Mobile/15E148 Safari/604.1
Sec-CH-UA-Full-Version: ""
Sec-CH-UA-Mobile: ?0
Sec-CH-UA-Model: ""
Sec-CH-UA-Platform: ""
Sec-CH-UA-Platform-Version: ""
```

<img width="496" alt="image" src="https://github.com/user-attachments/assets/c6caf22e-232a-48eb-b2aa-cb1c7c44f795" />


### Without empty Client Hints

``` yaml
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Mobile/15E148 Safari/604.1
Sec-CH-UA-Mobile: ?0
```

<img width="496" alt="image" src="https://github.com/user-attachments/assets/cf76e5e9-8688-431e-8d2c-3a191a5886a8" />


In both cases `Sec-CH-UA-Mobile: ?0` is present.
